spring:
 application:
  name: api-gateway
  
 #api gateway config
 	cloud:
 	 gateway:
 	  routes:
 	  	- id: order-service
 	  	  url: lb://ORDER-SERVICE
 	  	  predicates:
 	  	   - Path=/orders/**
 	  	-id: inventory-service
 	  	 url: lb:/INVENTORY-SERVICE
 	  	 predicates:
 	  	 	- Path=/inventory/**
 	  	 	
 eureka:
  client:
   service-url:
    defaultZone: http://localhost:8761/eureka	  	 	
